### ISSUE TITLE
settings.json information

### ISSUE THREAD

**Issue by zesty** [statiolake/vscode-rustfmt#4]
Readme should include:

```
"[rust]": {
    "editor.defaultFormatter": "statiolake.vscode-rustfmt",
    "editor.formatOnSave": true  //optional
}
```

**Comment by SergeyVolynkin** [comment]
It's also possible to enable the auto-formatting on save with [`rust-lang.rust`](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust) extension via 
```
  "[rust]": {
    "editor.defaultFormatter": "rust-lang.rust",
    "editor.formatOnSave": true
  }
```
![image](https://user-images.githubusercontent.com/34238697/149637072-f8c8d9f5-25c7-43b5-8c78-d68014d93269.png)

**Comment by statiolake** [comment]
Thank you! Sorry for taking a long time to fix this.
